import { Product, Category, ProductsAnalytics } from './productsApi';

export const mockCategories: Category[] = [
  {
    id: 'cat-1',
    tenantId: 'default-tenant',
    name: 'Electronics',
    slug: 'electronics',
    description: 'Electronic devices and accessories',
    isActive: true,
    sortOrder: 1,
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'cat-2',
    tenantId: 'default-tenant',
    name: 'Clothing',
    slug: 'clothing',
    description: 'Apparel and fashion items',
    isActive: true,
    sortOrder: 2,
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'cat-3',
    tenantId: 'default-tenant',
    name: 'Books',
    slug: 'books',
    description: 'Books and educational materials',
    isActive: true,
    sortOrder: 3,
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'cat-4',
    tenantId: 'default-tenant',
    name: 'Home & Garden',
    slug: 'home-garden',
    description: 'Home improvement and garden supplies',
    isActive: true,
    sortOrder: 4,
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'cat-5',
    tenantId: 'default-tenant',
    name: 'Sports & Outdoors',
    slug: 'sports-outdoors',
    description: 'Sports equipment and outdoor gear',
    isActive: true,
    sortOrder: 5,
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
];

export const mockProducts: Product[] = [
  {
    id: 'prod-1',
    tenantId: 'default-tenant',
    vendorId: 'vendor-1',
    categoryId: 'cat-1',
    name: 'Wireless Bluetooth Headphones',
    slug: 'wireless-bluetooth-headphones',
    sku: 'WBH-001',
    description: 'High-quality wireless headphones with noise cancellation technology. Perfect for music lovers and professionals.',
    price: '299.99',
    comparePrice: '349.99',
    costPrice: '180.00',
    status: 'ACTIVE',
    inventoryStatus: 'IN_STOCK',
    quantity: 50,
    lowStockThreshold: 10,
    weight: '0.8',
    searchKeywords: 'wireless bluetooth headphones audio music noise cancellation',
    tags: ['wireless', 'bluetooth', 'headphones', 'audio', 'premium'],
    currencyCode: 'USD',
    attributes: [
      { id: 'attr-1', name: 'Brand', value: 'TechCorp', type: 'text' },
      { id: 'attr-2', name: 'Color', value: 'Black', type: 'color' },
      { id: 'attr-3', name: 'Connectivity', value: 'Bluetooth 5.0', type: 'text' },
      { id: 'attr-4', name: 'Battery Life', value: '30 hours', type: 'text' },
    ],
    images: [
      { id: 'img-1', url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e', altText: 'Black wireless headphones', position: 1, width: 800, height: 600 },
      { id: 'img-2', url: 'https://images.unsplash.com/photo-1583394838336-acd977736f90', altText: 'Headphones side view', position: 2, width: 800, height: 600 },
    ],
    variants: [
      {
        id: 'var-1',
        productId: 'prod-1',
        sku: 'WBH-001-BLACK',
        name: 'Wireless Bluetooth Headphones - Black',
        price: '299.99',
        quantity: 30,
        attributes: [{ id: 'attr-5', name: 'Color', value: 'Black', type: 'color' }],
        createdAt: '2024-01-15T10:00:00Z',
        updatedAt: '2024-01-15T10:00:00Z',
      },
      {
        id: 'var-2',
        productId: 'prod-1',
        sku: 'WBH-001-WHITE',
        name: 'Wireless Bluetooth Headphones - White',
        price: '299.99',
        quantity: 20,
        attributes: [{ id: 'attr-6', name: 'Color', value: 'White', type: 'color' }],
        createdAt: '2024-01-15T10:00:00Z',
        updatedAt: '2024-01-15T10:00:00Z',
      },
    ],
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'prod-2',
    tenantId: 'default-tenant',
    vendorId: 'vendor-2',
    categoryId: 'cat-2',
    name: 'Premium Cotton T-Shirt',
    slug: 'premium-cotton-t-shirt',
    sku: 'PCT-001',
    description: 'Comfortable 100% organic cotton t-shirt available in multiple colors and sizes. Perfect for everyday wear.',
    price: '29.99',
    comparePrice: '39.99',
    costPrice: '15.00',
    status: 'ACTIVE',
    inventoryStatus: 'IN_STOCK',
    quantity: 100,
    lowStockThreshold: 20,
    weight: '0.2',
    searchKeywords: 'cotton t-shirt organic comfortable casual wear',
    tags: ['clothing', 't-shirt', 'cotton', 'casual', 'organic'],
    currencyCode: 'USD',
    attributes: [
      { id: 'attr-7', name: 'Material', value: '100% Organic Cotton', type: 'text' },
      { id: 'attr-8', name: 'Care Instructions', value: 'Machine wash cold', type: 'text' },
      { id: 'attr-9', name: 'Fit', value: 'Regular', type: 'text' },
    ],
    images: [
      { id: 'img-3', url: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab', altText: 'Cotton t-shirt front view', position: 1, width: 800, height: 600 },
      { id: 'img-4', url: 'https://images.unsplash.com/photo-1503341504253-dff4815485f1', altText: 'T-shirt fabric detail', position: 2, width: 800, height: 600 },
    ],
    variants: [
      {
        id: 'var-3',
        productId: 'prod-2',
        sku: 'PCT-001-S-BLACK',
        name: 'Premium Cotton T-Shirt - Small Black',
        price: '29.99',
        quantity: 25,
        attributes: [
          { id: 'attr-10', name: 'Size', value: 'S', type: 'size' },
          { id: 'attr-11', name: 'Color', value: 'Black', type: 'color' },
        ],
        createdAt: '2024-01-15T10:00:00Z',
        updatedAt: '2024-01-15T10:00:00Z',
      },
      {
        id: 'var-4',
        productId: 'prod-2',
        sku: 'PCT-001-M-BLACK',
        name: 'Premium Cotton T-Shirt - Medium Black',
        price: '29.99',
        quantity: 30,
        attributes: [
          { id: 'attr-12', name: 'Size', value: 'M', type: 'size' },
          { id: 'attr-13', name: 'Color', value: 'Black', type: 'color' },
        ],
        createdAt: '2024-01-15T10:00:00Z',
        updatedAt: '2024-01-15T10:00:00Z',
      },
      {
        id: 'var-5',
        productId: 'prod-2',
        sku: 'PCT-001-L-BLACK',
        name: 'Premium Cotton T-Shirt - Large Black',
        price: '29.99',
        quantity: 25,
        attributes: [
          { id: 'attr-14', name: 'Size', value: 'L', type: 'size' },
          { id: 'attr-15', name: 'Color', value: 'Black', type: 'color' },
        ],
        createdAt: '2024-01-15T10:00:00Z',
        updatedAt: '2024-01-15T10:00:00Z',
      },
    ],
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'prod-3',
    tenantId: 'default-tenant',
    vendorId: 'vendor-3',
    categoryId: 'cat-3',
    name: 'Advanced Programming Guide',
    slug: 'advanced-programming-guide',
    sku: 'APG-001',
    description: 'Comprehensive guide to advanced programming techniques and best practices. Perfect for developers looking to level up their skills.',
    price: '49.99',
    comparePrice: '59.99',
    costPrice: '25.00',
    status: 'ACTIVE',
    inventoryStatus: 'IN_STOCK',
    quantity: 25,
    lowStockThreshold: 5,
    weight: '0.6',
    searchKeywords: 'programming guide advanced techniques development coding',
    tags: ['books', 'programming', 'education', 'technology', 'development'],
    currencyCode: 'USD',
    attributes: [
      { id: 'attr-16', name: 'Author', value: 'John Doe', type: 'text' },
      { id: 'attr-17', name: 'Pages', value: '450', type: 'number' },
      { id: 'attr-18', name: 'Language', value: 'English', type: 'text' },
      { id: 'attr-19', name: 'Publisher', value: 'Tech Books Inc.', type: 'text' },
    ],
    images: [
      { id: 'img-5', url: 'https://images.unsplash.com/photo-1532012197267-da84d127e765', altText: 'Programming book cover', position: 1, width: 800, height: 600 },
      { id: 'img-6', url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d', altText: 'Book pages', position: 2, width: 800, height: 600 },
    ],
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'prod-4',
    tenantId: 'default-tenant',
    vendorId: 'vendor-1',
    categoryId: 'cat-1',
    name: 'Smart Fitness Watch',
    slug: 'smart-fitness-watch',
    sku: 'SFW-001',
    description: 'Advanced fitness tracking watch with heart rate monitoring, GPS, and 7-day battery life.',
    price: '199.99',
    comparePrice: '249.99',
    costPrice: '120.00',
    status: 'ACTIVE',
    inventoryStatus: 'LOW_STOCK',
    quantity: 8,
    lowStockThreshold: 10,
    weight: '0.15',
    searchKeywords: 'smart watch fitness tracking heart rate GPS health',
    tags: ['electronics', 'fitness', 'smartwatch', 'health', 'tracking'],
    currencyCode: 'USD',
    attributes: [
      { id: 'attr-20', name: 'Screen Size', value: '1.4 inches', type: 'text' },
      { id: 'attr-21', name: 'Battery Life', value: '7 days', type: 'text' },
      { id: 'attr-22', name: 'Water Resistance', value: '5ATM', type: 'text' },
    ],
    images: [
      { id: 'img-7', url: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30', altText: 'Smart fitness watch', position: 1, width: 800, height: 600 },
    ],
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'prod-5',
    tenantId: 'default-tenant',
    vendorId: 'vendor-2',
    categoryId: 'cat-4',
    name: 'Ceramic Plant Pot Set',
    slug: 'ceramic-plant-pot-set',
    sku: 'CPP-001',
    description: 'Beautiful set of 3 ceramic plant pots in different sizes. Perfect for indoor plants and home decoration.',
    price: '39.99',
    comparePrice: '49.99',
    costPrice: '20.00',
    status: 'DRAFT',
    inventoryStatus: 'OUT_OF_STOCK',
    quantity: 0,
    lowStockThreshold: 5,
    weight: '2.5',
    searchKeywords: 'ceramic plant pots indoor plants home decoration garden',
    tags: ['home', 'garden', 'plants', 'ceramic', 'decoration'],
    currencyCode: 'USD',
    attributes: [
      { id: 'attr-23', name: 'Material', value: 'Ceramic', type: 'text' },
      { id: 'attr-24', name: 'Set Size', value: '3 pieces', type: 'text' },
      { id: 'attr-25', name: 'Color', value: 'Terra Cotta', type: 'color' },
    ],
    images: [
      { id: 'img-8', url: 'https://images.unsplash.com/photo-1485955900006-10f4d324d411', altText: 'Ceramic plant pots', position: 1, width: 800, height: 600 },
    ],
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
];

export const mockAnalytics: ProductsAnalytics = {
  overview: {
    totalProducts: 5,
    activeProducts: 4,
    draftProducts: 1,
    outOfStock: 1,
    lowStock: 1,
    totalVariants: 8,
    averagePrice: 119.99,
    totalInventory: 183,
  },
  distribution: {
    byStatus: {
      ACTIVE: 4,
      DRAFT: 1,
      PENDING: 0,
      INACTIVE: 0,
      ARCHIVED: 0,
      REJECTED: 0,
    },
    byCategory: {
      Electronics: 2,
      Clothing: 1,
      Books: 1,
      'Home & Garden': 1,
    },
    byInventory: {
      IN_STOCK: 3,
      LOW_STOCK: 1,
      OUT_OF_STOCK: 1,
      BACK_ORDER: 0,
      DISCONTINUED: 0,
    },
  },
  trends: {
    daily: [
      { date: '2024-01-15', count: 2 },
      { date: '2024-01-16', count: 1 },
      { date: '2024-01-17', count: 0 },
      { date: '2024-01-18', count: 1 },
      { date: '2024-01-19', count: 1 },
      { date: '2024-01-20', count: 0 },
      { date: '2024-01-21', count: 0 },
    ],
    weekly: [
      { date: '2024-W02', count: 2 },
      { date: '2024-W03', count: 3 },
    ],
    monthly: [
      { date: '2024-01', count: 5 },
    ],
  },
  topProducts: [
    {
      id: 'prod-1',
      name: 'Wireless Bluetooth Headphones',
      sku: 'WBH-001',
      viewCount: 245,
      orderCount: 18,
      revenue: 5399.82,
    },
    {
      id: 'prod-2',
      name: 'Premium Cotton T-Shirt',
      sku: 'PCT-001',
      viewCount: 189,
      orderCount: 32,
      revenue: 959.68,
    },
    {
      id: 'prod-4',
      name: 'Smart Fitness Watch',
      sku: 'SFW-001',
      viewCount: 156,
      orderCount: 12,
      revenue: 2399.88,
    },
  ],
};